### ISSUE TITLE
Create Log File - mp_team1 domination

### ISSUE THREAD

**Issue by dudleycodes** [LacledesLAN/sourceseer#1]
**Setup**

1. Create a *stock* server with default rules; use whatever map you'd like.
2. Set `mp_teamname1` to `alpha` (this is the team that starts on CT).
3. Set `mp_teamname2` to `bravo` (this is the team that starts on T).
4. Set `mp_match_can_clinch` to 1.

**Match Requirements**

- [ ] Play only 16 rounds.
- [ ] mp_team1 should win the first 16 rounds.
- [ ] Kill the server during post-match freeze time.

**Comment by dudleycodes** [comment]
Note: warmup was a 5 minute timer

**Comment by JustinBenedick** [comment]
[L172_030_014_010_27015_201908041813_000.log](https://github.com/LacledesLAN/sourceseer/files/3465182/L172_030_014_010_27015_201908041813_000.log)
