### ISSUE TITLE
Create Log File - mp_team2 clinch (no overtime)

### ISSUE THREAD

**Issue by dudleycodes** [LacledesLAN/sourceseer#2]
**Setup**

1. Create a *stock* server with default rules; use whatever map you'd like.
2. Set `mp_teamname1` to `alpha` (this is the team that starts on CT).
3. Set `mp_teamname2` to `bravo` (this is the team that starts on T).
4. Set `mp_match_can_clinch` to 1.

**Match Requirements**

- [ ] Play at least 26 rounds.
- [ ] Mix up the different ways to win rounds (defuse, explodes, time runs out, team wipe out, team suicide, etc)
- [ ] mp_team2 should win with 16 rounds; but mp_team1 should win 10 rounds.
- [ ] Kill the server during post-match freeze time.

**Comment by JustinBenedick** [comment]
[L172_030_014_010_27015_201908041830_000.log](https://github.com/LacledesLAN/sourceseer/files/3465192/L172_030_014_010_27015_201908041830_000.log)
