### ISSUE TITLE
Create Log File - mp_team1 clinch in overtime

### ISSUE THREAD

**Issue by dudleycodes** [LacledesLAN/sourceseer#3]
**Setup**

1. Create a *stock* server with default rules; use whatever map you'd like.
2. Set `mp_teamname1` to `alpha` (this is the team that starts on CT).
3. Set `mp_teamname2` to `bravo` (this is the team that starts on T).
4. Set `mp_match_can_clinch` to 1.

**Match Requirements**

- [ ] Tie the first 30 rounds
- [ ] Mix up the different ways to win rounds (defuse, explodes, time runs out, team wipe out, team suicide, etc)
- [ ] mp_team1 should win in overtime.
- [ ] Kill the server during post-match freeze time.

**Comment by JustinBenedick** [comment]
[L172_030_014_010_27015_201908041850_000.log](https://github.com/LacledesLAN/sourceseer/files/3465219/L172_030_014_010_27015_201908041850_000.log)

**Comment by dudleycodes** [comment]
> [L172_030_014_010_27015_201908041850_000.log](https://github.com/LacledesLAN/sourceseer/files/3465219/L172_030_014_010_27015_201908041850_000.log)

Not a good log file - overtime didn't trigger

**Comment by JustinBenedick** [comment]
[L172_030_014_010_27015_201908041850_000.log](https://github.com/LacledesLAN/sourceseer/files/3465234/L172_030_014_010_27015_201908041850_000.log)

**Comment by dudleycodes** [comment]
You gave me the wrong one again...

**Comment by JustinBenedick** [comment]
[L172_030_014_010_27015_201908041913_000.log](https://github.com/LacledesLAN/sourceseer/files/3465239/L172_030_014_010_27015_201908041913_000.log)
