### ISSUE TITLE
Create Log File - Single Tourney Chaotic Play, Full Server

### ISSUE THREAD

**Issue by dudleycodes** [LacledesLAN/sourceseer#4]
**Setup**

1. Create a **tourney, not warmod**, use a **stock** map.
2. Set `mp_teamname1` to `alpha` (this is the team that starts on CT).
3. Set `mp_teamname2` to `bravo` (this is the team that starts on T).
4. Fill all remaining server slots with bots.

**Match Requirements**

Play until the match ends; include the following information when posting the log file to this issue:

- [ ] How many total rounds were played.
- [ ] For each round won note the winning team.
- [ ] Note the final scores.

**Comment by JustinBenedick** [comment]
![20190804151629_1](https://user-images.githubusercontent.com/1591013/62428758-fb766480-b6ca-11e9-9124-5d8e4262375d.jpg)

**Comment by JustinBenedick** [comment]
[L172_030_014_010_27015_201908041942_000.log](https://github.com/LacledesLAN/sourceseer/files/3465290/L172_030_014_010_27015_201908041942_000.log)
