### ISSUE TITLE
Create Log File - 3x Tourney Play

### ISSUE THREAD

**Issue by dudleycodes** [LacledesLAN/sourceseer#5]
**Setup**

1. Create a **tourney, not warmod**, use any map.
2. Set `mp_teamname1` to `alpha` (this is the team that starts on CT).
3. Set `mp_teamname2` to `bravo` (this is the team that starts on T).

**Match Requirements**

Play out three full matches; one team should win the first and third match while the other should win the second match. Include the following information for each match when posting the log file to this issue:

- [ ] How many total rounds were played.
- [ ] How many rounds `mp_team1` won.
- [ ] How many rounds `mp_team2` won.

**Comment by JustinBenedick** [comment]
[L172_030_014_010_27015_201908042058_000.log](https://github.com/LacledesLAN/sourceseer/files/3465344/L172_030_014_010_27015_201908042058_000.log)

**Comment by JustinBenedick** [comment]
game one: team1 won 16,  team 2 won 0
game two team 1 won 0, team 2 won16
game three: team1 won 16,  team 2 won 0

**Comment by dudleycodes** [comment]
Reopened; as log does not match intended scenario.  In this log `mp_team2` won matches 1 and 2 while `mp_team1` won match 3.

Need the wins to alternate to test tournament clinching logic.  Under normal scenarios the server would automatically shut down after the 2 match; as `mp_team2` would have gotten the clinch.

**Comment by JustinBenedick** [comment]
![20190804191115_1](https://user-images.githubusercontent.com/1591013/62431584-42298600-b6ee-11e9-8021-a398705a0e5f.jpg)

**Comment by JustinBenedick** [comment]
![20190804191941_1](https://user-images.githubusercontent.com/1591013/62431591-4a81c100-b6ee-11e9-8c8e-5a922bf3a874.jpg)

**Comment by JustinBenedick** [comment]
![20190804192902_1](https://user-images.githubusercontent.com/1591013/62431594-4f467500-b6ee-11e9-9e2a-216a0bc28477.jpg)

**Comment by JustinBenedick** [comment]
[L172_030_014_010_27015_201908050002_000.log](https://github.com/LacledesLAN/sourceseer/files/3465510/L172_030_014_010_27015_201908050002_000.log)
