### ISSUE TITLE
Create Log File - All the Conditions

### ISSUE THREAD

**Issue by dudleycodes** [LacledesLAN/sourceseer#6]
**Setup**

1. Create a *tourney, not warmod*, use any map.
2. Set `mp_teamname1` to `alpha` (this is the team that starts on CT).
3. Set `mp_teamname2` to `bravo` (this is the team that starts on T).

**Match Requirements**

Play out enough matches so that each team hits all the win/lose conditions.  For example, both teams should win be defusal once, win by elimination once, etc.  For each round note the the win condition and team that triggered it.

**Comment by JustinBenedick** [comment]
[L172_030_014_010_27015_201908042025_000.log](https://github.com/LacledesLAN/sourceseer/files/3465305/L172_030_014_010_27015_201908042025_000.log)

**Comment by JustinBenedick** [comment]
![20190804151629_1](https://user-images.githubusercontent.com/1591013/62429014-a50b2500-b6ce-11e9-9379-bf7117ed9134.jpg)

**Comment by TonyDiPietri** [comment]
Round 1: Team 1 wins by defusal
Round 1: Team 1 wins by
Round 1: Team 1 wins by
Round 1: Team 1 wins by
Round 1: Team 1 wins by
Round 1: Team 1 wins by
Round 1: Team 1 wins by
Round 1: Team 1 wins byRound 1: Team 1 wins by

**Comment by JustinBenedick** [comment]
![20190804154228_1](https://user-images.githubusercontent.com/1591013/62429069-675acc00-b6cf-11e9-84ac-f58aec319859.jpg)
