### ISSUE TITLE
Create Log File - 5x Tourney Chaotic Play, Full Server

### ISSUE THREAD

**Issue by dudleycodes** [LacledesLAN/sourceseer#7]
**Setup**

1. Create a **tourney, not warmod**, use **stock** map rotation.
2. Set `mp_teamname1` to `alpha` (this is the team that starts on CT).
3. Set `mp_teamname2` to `bravo` (this is the team that starts on T).
4. Fill all remaining server slots with bots.

**Match Requirements**

Play five full matches in a row; for each match note:

- [ ] How many total rounds were played.
- [ ] Note the final scores.

**Comment by JustinBenedick** [comment]
![20190804171237_1](https://user-images.githubusercontent.com/1591013/62431037-78183b80-b6e9-11e9-8fef-25692560d3c8.jpg)

**Comment by JustinBenedick** [comment]
![20190804173537_1](https://user-images.githubusercontent.com/1591013/62431038-7c445900-b6e9-11e9-8548-b622c0131680.jpg)

**Comment by JustinBenedick** [comment]
![20190804175939_1](https://user-images.githubusercontent.com/1591013/62431043-81090d00-b6e9-11e9-8b1a-79529e78ff04.jpg)

**Comment by JustinBenedick** [comment]
![20190804182346_1](https://user-images.githubusercontent.com/1591013/62431045-85352a80-b6e9-11e9-96d6-16fc06059856.jpg)

**Comment by JustinBenedick** [comment]
![20190804185409_1](https://user-images.githubusercontent.com/1591013/62431050-8d8d6580-b6e9-11e9-8f86-c51faee9969e.jpg)

**Comment by JustinBenedick** [comment]
[L000_000_000_000_0_201908042143_000.log](https://github.com/LacledesLAN/sourceseer/files/3465463/L000_000_000_000_0_201908042143_000.log)

**Comment by JustinBenedick** [comment]
[L172_030_014_010_27015_201908042143_000.log](https://github.com/LacledesLAN/sourceseer/files/3465467/L172_030_014_010_27015_201908042143_000.log)
